name: Architecture Check

on:
  pull_request:

jobs:
  architecture:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: builditwithgk/repo-cartographer@v1
        with:
          path: .
          level: high